directories:
  output: dist-electron-out
  buildResources: build
appId: com.knoksen.cyberagentsdashboard
productName: Cyber Agents Dashboard
protocols:
  - name: CyberDash Protocol
    schemes:
      - cyberdash
files:
  - filter:
      - dist/**
      - electron/**
      - index.html
      - package.json
      - LICENSE.txt
asar: true
compression: maximum
publish: null
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
  artifactName: ${productName} Setup ${version}.${ext}
  icon: build/icon.ico
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: CyberSec Dash
  license: LICENSE.txt
electronVersion: 37.3.1
